### ISSUE TITLE
Too long compilation time

### ISSUE THREAD

**Issue by simnalamburt** [PistonDevelopers/texture_packer#45]
Using all default features of `image` crate leads this crate to bloated compilation time which is undesirable. We should opt-in those featuers. Below codes are the brief example of how to do it.

```
[features]
## create a feature in your app
default = ["gif_codec", "jpeg", "ico", "png_codec", "ppm", "tga", "tiff", "webp", "bmp", "hdr"]

gif_codec = ["image/gif_codec"]
ico = ["image/ico"]
jpeg = ["image/jpeg"]
png_codec = ["image/png_codec"]
ppm = ["image/ppm"]
tga = ["image/tga"]
tiff = ["image/tiff"]
webp = ["image/webp"]
bmp = ["image/bmp"]
hdr = ["image/hdr"]

[dependencies]
image = { version = "0.10.0", default-features = false }
```

###### References
- http://doc.crates.io/manifest.html#the-features-section
- https://github.com/rust-lang/cargo/pull/712

**Comment by bvssvni** [comment]
Isn't there a way to disable default cargo features and then enable them by adding a dependency to the library in the top project?

**Comment by simnalamburt** [comment]
@bvssvni It's possible but I intensionally choosed not to since it's unnecessary backward compatibility breakage.

**Comment by bvssvni** [comment]
Don't worry about breaking stuff! We'll just bump the version and existing code will continue to work with the old version.

**Comment by simnalamburt** [comment]
OK then. If we enhance documentations and examples, maybe it can be a good chance for texture_packer to be **1.0.0**

I'll propose a PR soon.

**Comment by bvssvni** [comment]
We don't need 1.0.0 yet, 0.9.0 will work just fine because it is the first non-zero number that is interpreted as a breaking change by Cargo. However, it would be nice to do as you say.

**Comment by simnalamburt** [comment]
Oops, sorry. That was a mistake
