### ISSUE TITLE
Make keys generic instead of only `String`s

### ISSUE THREAD

**Issue by HeroesGrave** [PistonDevelopers/texture_packer#48]
Some applications may have more efficient ways to identify textures (eg: simple integer keys). Strings are a bit of a waste.

**Comment by simnalamburt** [comment]
@HeroesGrave Agreed. I want to fix this too

Currently I'm not able to work on this issue for a monent. But if you propose a alternative API design proposal or even a PR, I'm pretty open to accept it. Thanks!

**Comment by bvssvni** [comment]
@botahamec Yes. Thanks for noticing.
