### ISSUE TITLE
Outdated image crate.

### ISSUE THREAD

**Issue by LuisAyuso** [PistonDevelopers/texture_packer#49]
the image crate is outdated (0.10) when currently the version is (0.14)
The code fails to compile as it prompts:
`trait image::image::GenericImage is not implemented for image::DynamicImage`

It makes me wonder why there is so much code wrapping the image library. Like features to support different formats. Since the basic idea of this library is to deal with rectangles, It seems to me like an overkill.

**Comment by bvssvni** [comment]
Yeah, you can just add the "image" crate to the project's Cargo toml to get the features.

**Comment by LuisAyuso** [comment]
Yes, I can see that. The question is why?
The features option adds complexity to this crate and I can not see the use for it.

**Comment by bvssvni** [comment]
Agreed. I'll make a PR soon.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/texture_packer/pull/50
