### ISSUE TITLE
Is TexturePacker intentionally not storable in a struct?

### ISSUE THREAD

**Issue by mistodon** [PistonDevelopers/texture_packer#56]
Because `SkylinePacker` is private, the type returned by `new_skyline` cannot be named and so can't be stored in a struct.

This seems... odd to me, and it's sort of preventing me from building up an atlas procedurally when I don't have all the textures within the scope of one function.

Should that type be public?

**Comment by BourgondAries** [comment]
It should now be possible to fit a packer inside a struct, can this issue be closed?
